@startuml
Shop "1" *-- "many" Product : has
Shop "1" *-- "many" Customer : has
Shop "1" *-- "many" Basket : has
Shop "1" *-- "many" Supplier : has
Basket "1" *-- "many" Product : has
Shop "1" *-- "many" Register : has
Register "1" *-- "1" Basket : has

Shop : ArrayList<Product> products
Shop : ArrayList<Customer> customers
Shop : displayProducts()

Customer : String userName
Customer : String id
Customer : toString()

Product : String prodName
Product : float prodPrice
Product : String prodType
Product : tryProduct()

Supplier : String supName
Supplier : float shippingCost
Supplier : String supCountry
Supplier : String shippingMethod
Supplier : int shippingTime
Supplier : refillShop()

Basket : ArrayList<Product> products
Basket : displayBasket()

Register : int regNr
Register : boolean selfScan
Register : chechOut()
@enduml
